# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /etc/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Start Nginx when the container has started
# debian
CMD ["nginx", "-g", "daemon off;"] 

# oracle linux
#CMD ["nginx"]