apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service-deployment
  labels:
    app: file-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: docker.io/meza360/azure-file-service:latest
          env:
            - name: LOG_ROOT_PATH
              value: /mnt/volumes/vazurefileservice/log
            - name: CA_CERT_DATA
              value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSi9oYTlJckloSmN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1UWXdORFEzTlRaYUZ3MHpOREV5TVRRd05EVXlOVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURUcWtqZkVDeDlKazRnV3dpVmJJajh3RUphanlUc0wzaDVWSXpuN1FJZ0J5Tm9pNzFWRVVlVWdGSDMKUjMwR1FLSFo0azVybkNhOEphZUZHMGtiVFlIM2cwRzF3NkVPLzJnaTIyam5VaUEwVXZOUm9DcXRiQVNKM1A4awpZVmxaWDZqOGZOQWViN2lsM0diaTVIWXlsa3FWTXc4TWtlTkJiSytLSmRuZHZGa3hoT2hzdDh3NTFnaEU3TzF3CjBsS0ttUmw2V3J0YlJxdnJ6Y1Fyb3BLT2Nlck1YREpqWU9hS2dlc1Izdy9LQlhRdE1GcDArVGFFQi93dVVHVisKNWpUWFAzTkNIc0RLd3RBYTROdlBuQk12Y1JQS1Y4c1JUK2NYdFhCSlAzQ2dpQUZFaTdsV3N6aEhMbENSd1NhawpqKzJrcXd3SVpROHRaZkdPaDZyQTdBcUZVS2VOQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSaXlhQnFTbmxxWWxJZGJFbnJaa1p5c1VKdDlEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQS92TVpNZWdESwo5cmhxZXVnZVBsWW1Mc3dSNSt1TmxmcmVxL3J6RWx5ZnY4TVZERmF0N0t0cXpQTEJNd0VGcVdHT1hJR1BlU1RpCm0vcFJTTUcxazNFY0RoVEVKWjVYMUhsL3dGaXNoYjIvZU0rL0dvcUpOekhnNlcybVZtK1V6WjNvRFIweGdHUTIKbmRaMFRUQW9XZVJKTjlQZWxURHpqNEh3aTd2dExJL0pLdDdNTVNuczZQWWNUSWxmQUIxS3JCSnN5bWczTnNZZQpMbXdteXdZNkdZTGVBUnk3d2RkQkozdnhNOFk2ZHhLdEVrWTdQRmhvWlJsbmJkVHdTUjVXQ3NtbmFJRTB2aVlKClNhZys2dllnb0VyUnZQODRQcWVHemxpQWpPUGx5NlljdUFLYk1Xd1ZHdFROTEVXdG9hV2I4dmJYU09MRXpIb3YKNjdPclBHcEEvV3d1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            - name: CLIENT_CERT_DATA
              value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJZUVKaFkzamQ0djB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1UWXdORFEzTlRaYUZ3MHlOVEV5TVRZd05EVXlOVFphTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDZ1gxZmgKdXRPTTJRLzBuc0tPOHFBeDk1Z3kzUnZaWUpiYmNRcUkzcitrR3R6K1ZCUlg4bjA2SGJsaGV5RWVHTlZMa0I3cAp6cjl6d0NjT2sxOEM3MnVWV1l3WlBlQzNNWTdmTkcrSTZqdERocnVHUWl5cXZhcTIwTFdjN3crZlh1ZHNwdmRBCkcycEFEdmQ3NFBHc0VwdDRFK0dnN1NkeHUrTjAyS0x2SUE1VzU1OVh3RndCSUxLendQd3g5WGJrMVI5Q25OdFcKQzBSakFPUlQ0ODBWd0labFNHL2JjTVFXRktOcTJNeWNCN2ZDeTVjR2V6VW1waC9xVnFvRHhHK1ltb055OE54ZwpDT01zcGhib3JRTkZjNHZSQjBnanV2aWppampHa3dreWg0MlF2WTZocTBWYTRKNWpGUi9PaXFnTitEMXY3OThGCjk5eE5FeGkwRXRVckE4eDFBZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkdMSm9HcEtlV3BpVWgxcwpTZXRtUm5LeFFtMzBNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNsRVFEdm1IT09TdDVvVk1TVFNvbXRkeWxjCmhqNjNUaU9XSytlSzEzVk9WTmdOTWVPa2kxa3NUUlQrYXNHRnJlbmVPZGptMXFUZm4zOVM3cm9JMWlrRTRZZXcKVXVaYVlFd0l4Rm40eE1kK3EwRXZmMXFOL3JkbTN4V21BRUJGNkJrSmJBZ2REYnNMUEM0WjVodm0raEhmMWtmZgpMNjJVNW93RDZkdlMvSmJ0b0JZOS9mc3hSTFFwMHFNMUlDaEQ0em10RUh6S2NyZTdoQUZwdmlYN1hoNms5YTZoClFnYzRGM2grd002a1hDd0l2L0k0ZHVNREZ1Ykh0ZWt3bWdWNWZjaTVCVmJJQ2FZY0dKUVlmU0phc0x1ZW9WZW4KMTlvV0RNai9VUDVPUFVxTHlKbW02VjFlS0NtRUI4c0t5QmRjaTI5SHRDVE84WFp0RnFxY2pydEswQnArCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            - name: CLIENT_KEY_DATA
              value: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBb0Y5WDRiclRqTmtQOUo3Q2p2S2dNZmVZTXQwYjJXQ1cyM0VLaU42L3BCcmMvbFFVClYvSjlPaDI1WVhzaEhoalZTNUFlNmM2L2M4QW5EcE5mQXU5cmxWbU1HVDNndHpHTzN6UnZpT283UTRhN2hrSXMKcXIycXR0QzFuTzhQbjE3bmJLYjNRQnRxUUE3M2UrRHhyQktiZUJQaG9PMG5jYnZqZE5paTd5QU9WdWVmVjhCYwpBU0N5czhEOE1mVjI1TlVmUXB6YlZndEVZd0RrVStQTkZjQ0daVWh2MjNERUZoU2phdGpNbkFlM3dzdVhCbnMxCkpxWWY2bGFxQThSdm1KcURjdkRjWUFqakxLWVc2SzBEUlhPTDBRZElJN3I0bzRvNHhwTUpNb2VOa0wyT29hdEYKV3VDZVl4VWZ6b3FvRGZnOWIrL2ZCZmZjVFJNWXRCTFZLd1BNZFFJREFRQUJBb0lCQVFDSFpuZ29XVGhyWG9pZQpHN3hnUEhFTVB1TDlicmtvbXVoRGRmbFMvZDRIaTdheDlBTUpEZTYwdG92aHhiZDhWYk1nRFJwTWhRWVhrRkJwCmVmdHAyd0tXSWZpckJ4ZEhGRXh3SHpGY0E0YnR5RDlqWjFPWEJIT3h6aHpIMXY3MXE0YndzVGRucEwzY1A4YXIKakl2K24rY3JSbjNsQk5XY3JPbXBxWTVISG1WODhOTzJpYW1ycHQ2UjJMbzhCNVFLQndtMmN0SXhYMXNLU3AvUgpaNEwwbmZsZXVZdEkvbnAxRlB2UWdvcHB2K0M4N3hSVFY3R2pXVStFNXAvQ0E4bWxFNDYyYzgwSitQN0VubTNGCjZ6dDR4VytYTDB0UDZvcElwTGZObEw2UzkzUTZQQWtnazFzYUNnYTlLRndqK0pOUXRtOXg0amRMMTVLOGFSVG4KWEFnQ0tXY3hBb0dCQU1PRkhZbmV3NlhKS2h0OUVKYWNZNW1PQmxEbVdkVjZyZVBXZkJESW52dFRyZXNMaXJWRQo2RHNpYnVwbWhwQ3dxSzc1QitsWGpOYi81RHBDbHptNVp4ZHQyOEJMR0ZIOGlZZzQwWmh3NTUwSEI4aU43TTQ5CnBoT2JsZEN5UnJ0Z3htVjZydU1kWlc1cUNsZklVWFpKRUhBK1N1MUZZQUtMczROYlJTa1ppMS9mQW9HQkFOSDYKOUl0Z3Z3enB2Y2NxQ0JmMkprSDNBVnR0MFJpTWVBckhnaHNKQ3ByQ1R2S1VxM2dNQWhRemVNNEpIWW9PNWdobwp2aUc2elZJdFpMMGIwc29XRVNZaFQ4dks0c3QramhDalJKN0NaL1JiVENpODYyQ05QWlc3YmZyYmRsTzAwbnZmCmxlNzA5N2E5bnp2M1A1VWJIbmdMVDBwN043ZFFuVUptR3ZDSU00NHJBb0dBUHBqQnFrQk50eWcrZU9xRGd4U3kKdHBqSDRPSys1Q0FReUI4RlBZSmRrKzFvZ3hZQTVLUVpEY1dxYVJWR0E5RHJVSW1lUk5DbzRMU3dadzZteCs1WgoyU0JzK0pXU1JiMXFjdGh1RWpZamtSeU5HMktFN0VyRWZ3YVM0bXdSUlRCb2xGakE0U21xTGIxNWJqMU9CMmJCCkFvNlBBb1B4aHg4ZTYvRXVwVWZ1WFZVQ2dZQWJNVHVQL1NSZ29MaHgzVkNWQWN4c2lIZEZodEFvTkxDcS9MRXQKblJzaGRYNVJ6Y3p5eStOTkNHbGhqUzZsSFU3TzBmbWxWcEtXVE1pWjhNdDRYaWswWGVYK2h6U2RrN01FRnBDaApXcDJwdUZVQmhZMlp3RkMwWGtSYzB5VGNyRE1CMWErTjlXMUszZjJMLzNYZGNsaWN4U0lzakE1b0QrbDltc2xzClVzY1Nad0tCZ0hkei9MTG81bk1mT1pWRm1KMFNtK0FoakNHTThIWWZ1bGFqbUpJejBXRzRKRGFERTRFMGQyTk8KeVpKT280UUdFM1dLdDIwd3lnTHl5VzljdjF3MU9rc0RGd0ZXYnZ1SjdwRFhUdWxvbmk4ZDh0SkdiY3dYdk4xaQpHWFF4T1c4clJSdU5maWVFTmFDN2RxOVdwd2pvQzB5NklOc2EyS0JuZm1oQlplbkYxaUkwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
            - name: MASTER_URL
              #value: https://192.168.0.200:7002
              value: https://gt2-control-plane-01.gt2software.dev:7002
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2000m"
              memory: "2048Mi"
            requests:
              cpu: "1000m"
              memory: "1024Mi"
      #      imagePullSecrets:
      #        - name: miclarocore-credentials
      #dnsPolicy: None
      #dnsConfig:
      #  nameservers:
      #    - 192.180.0.62
      #  searches:
      #    - ns1.svc.gt2software.dev
      #    - gt2software.dev
      restartPolicy: Always
