apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service-deployment
  labels:
    app: file-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service-container
          image: docker.io/meza360/azure-file-service:latest
          # environment variables defined by user
          env:
            - name: LOG_ROOT_PATH
              value: /mnt/volumes/vazurefileservice/prd/log
            - name: DEPLOYMENT_ARCH
              value: K8S
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          # environment variables from other sources
          envFrom:
            - configMapRef:
                name: api-configmap
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      #      imagePullSecrets:
      #        - name: miclarocore-credentials
      #dnsPolicy: None
      #dnsConfig:
      #  nameservers:
      #    - 192.180.0.62
      #  searches:
      #    - ns1.svc.gt2software.dev
      #    - gt2software.dev
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  LOG_ROOT_PATH: /mnt/volumes/vazurefileservice/log
  CA_CERT_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWE51ck1JYzNzM2N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1UWXdOalEwTWpaYUZ3MHpOREV5TVRRd05qUTVNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMyMk9MUUxXbVlsZjl1b2FLL2I1Q09rN1RSdFBZM0pzYjVJdXVseld1cHhWZVBueGtqOTN6VmtINk4KNXFBQkJrR0hydmFGUzZtNmt5Y3ZwWm9ZQW9NZm5qUklaV1dnN0R3eHl5UFNOU0RVN2RKYVExZHU2azl6RTlYdwpXNEVwdVVZa0djNkl2Rnh0RWVnZGVqT0dET3YwWnk5ZDlTbzFYRVVlMldNNnl4MlRsWEkxUjdWR2VXRTlRN3NWCkJLRGJjeVRmOXJsTTMzbHAyeTJqY0xmNUxva1d0T056cE80VHc4QXpMdFVZMVBxS0VEQnErbW9odkZiTVRhV1cKUUpFWkNCZlgzbjRoNjJqcmdFdTdPT29MZjdOcEtmbDNHMUxWUzBJbHUxUEZJWjJKakZzTUdpOFk5V2VZbFNxMgp0VFpsTVhGbzBMeC9yS09uMFJKem45MFZQY1ROQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUFk1RWt0Z1lXdG1rakRKRCtQVXdCT2F4Y1R6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ01kRi91eUMzMApVME16TVFRTmdTOUtZcXN5U2tTYzdLNjhBY3p5R1h0di9UTitvd2J6RmtRT3czdUJSaHFjTElBT3BPNExUU0VCCnUwejNWSlZwMFZhZDIrTFJ1M0E0UFJCVEdHVitJY1FpK2kxZlowTEhKUXVnWmJMcUdWY05FYSsyeC9JOFhtMWkKNmRhV3JkK1daM2pqWEpCRnJ6dVBQa1ZjTXM4RGMwNHZrZnZCM1A4bDQydTVPRGkxZFhzRUc3TmROSzN6TG0zQwowNHZDRVlFV080V0YxQ0lpUDFVeldhWXR1Y3BqaTFrNmtXZllkdzB5dUw5dnpnZFdpeGtQQUxNOGZVRklEODUxCjBsTlZqYzhMUFlTOUEybU5JVG1wVGI1RWlxTWdGZE94QzZvRFVYNWZHdnpseXptbHpVUk9VbFlHQmtxNGYyRFkKQUYzVlMvZkZyd0JmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  CLIENT_CERT_DATA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lJTmJYUXhxTnBYRzh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFeU1UWXdOalEwTWpaYUZ3MHlOVEV5TVRZd05qUTVNalphTUR3eApIekFkQmdOVkJBb1RGbXQxWW1WaFpHMDZZMngxYzNSbGNpMWhaRzFwYm5NeEdUQVhCZ05WQkFNVEVHdDFZbVZ5CmJtVjBaWE10WVdSdGFXNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFET0dROHMKOHJPSE92SVIza1p1azlrZm83dWZTaHZhZzQrY0dGeWhVM2g3OU5uZG5xU1hmMkVDMC9Fa21JcE1JTi9lUkRvQgp6c2pQQlFHYS9ZRS9pYWJTVzQ3TnphQld2bGV1ZUFBMjlZTllOeGswUGVwbVAxOERXTWpPaUlGY2EvcDlQWDBwCmFVUkFjdCsyOHArR3JQVTJrSzRMUUswMHVFajg4TGtTUVM1ellQOFBrRVhtNGFKTmZpeVpXTkV3cTJiaTlVRkoKK1VxT1BJWHl6Y0pTMjJmMzhFdnphd0x3Z0swV1FwSFA0R3greDZhSWwvT2JRampjaEZuVlZYTXRXSU5Qd2VCSgpVMU1PZW9oVWwyUjcyMGFKbURoa2d3ellXVHY0YVRnNk5KNVVxZytaU3Q5QThPMTVNT3ZKdWFoWURzMlQ4MjI3CnR1UGZOOHBiVkJWUTc1bi9BZ01CQUFHalZqQlVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkE5amtTUzJCaGEyYVNNTQprUDQ5VEFFNXJGeFBNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUMwVFhxeVhTTEdzTWt6S3MxT0NuYkg1T0d1CkYrMTFOcDU3NWwyRitpcElRVFplME9Jc0xucTlPTmdZUERSdmtDWnh4YUMwTW5iWlBkSnBmM0diZGljM2dKRFQKWWNIWFFkbjdoc0kxYjNFeEFkcTUvWXpCam0zMHA5RklRVGh4ZDZtUEN2dWx0ZlVlNWtMVWVsSmlrNVV3SnJQRQpBL1kvN1V5aXF4Y1FyMldnb3NpR21ZdFZFdktoQlUyQVQrMVdOeFhBRHBVNFBmMVBHQklabk5laUd0Z1R4RWtoCjU0cFNtbjlLdVpNbVdsd0NFNDk2bDdNcTNON0xybjBDT0RCZG1nb1lPV2pNM2ZiWVJCMVgxQXQyYzJQYmU0enkKajdER1hIWXd4TEtQbFYxdTlNbHZBRWFaUjlHQ2Voci9KZU92ZEtkYWJxcjI2bDd1ZjFZNU5lcjRLc2I2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  CLIENT_KEY_DATA: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBemhrUExQS3poenJ5RWQ1R2JwUFpINk83bjBvYjJvT1BuQmhjb1ZONGUvVFozWjZrCmwzOWhBdFB4SkppS1RDRGYza1E2QWM3SXp3VUJtdjJCUDRtbTBsdU96YzJnVnI1WHJuZ0FOdldEV0RjWk5EM3EKWmo5ZkExakl6b2lCWEd2NmZUMTlLV2xFUUhMZnR2S2ZocXoxTnBDdUMwQ3ROTGhJL1BDNUVrRXVjMkQvRDVCRgo1dUdpVFg0c21WalJNS3RtNHZWQlNmbEtqanlGOHMzQ1V0dG45L0JMODJzQzhJQ3RGa0tSeitCc2ZzZW1pSmZ6Cm0wSTQzSVJaMVZWekxWaURUOEhnU1ZOVERucUlWSmRrZTl0R2laZzRaSU1NMkZrNytHazRPalNlVktvUG1VcmYKUVBEdGVURHJ5Ym1vV0E3TmsvTnR1N2JqM3pmS1cxUVZVTytaL3dJREFRQUJBb0lCQVFDRytSSmZOWE10bFFVRApmclpScExJRmJvMXBmSGRSVytlcEtxcy9YQk1EMnc3emZQbjkzWVlDL0JwcEJSMU5UaHBPemcvUEwwV0RqcHZHCmpVOGY5VjR6VlpMb1pVb2toUE9YWnk5OHpyeitBTmVZeHhQRGNxMGUyLzVtaEM5ei82TkVjZ2lPSGtwOGlyN0kKYVl6Zi9sVjVMcmRNMTBhWHlEakVya0lHR25uNVJOY0NMMjJ6L3dENTU5N0tiMlJlL1VyUnRNcHJiTlNrbklYbQp4Y1RjV0phdFEvWXlpdmFJcjlFemxaeHZxZ0x3ZndQdXk4NGpNY0FPSC9SL1dKOWlnd0hBS1NMOVBZN0w5NXdOCjM5eFMrQVN2NWNmTVk3QUlrcWs0UVZNaURxSWpNWlFodC9hdExIVGZHbjRiRVVHYSt4ZVB6cHhpbi9hVEcxTUUKcXYrd0ZOZ0JBb0dCQVBnd2IrQSs0K1c3K1BtL202N1BFTFJVWGFpOEl1Q0ZrcTFhR20xTEh1L1RFV3RGQXB3TgpHSWdOS1dHME9QYldxaXhSOFJkbzBRQkp1RVR4aDFBVWtBc2pMQ2JWUWFVMUFWOUEyVHZyMjFUQytWa1Nqdm5aCktRSGVnREtxbk9nUDZuRXVTRkwrdVhlT21FczNHVXlIYzRTNXhaL2UvMGhJTFFrV2NudjBaNEovQW9HQkFOU1YKZ2svNDhEUC9kRm01MDhKV1ZVNkFSNHpvN3VSM1cvVWNoUkt4QUtOdmxFYWM3OFNJelh2UDJHK3UwbGRqcllIMAo1bGQwaDlHK3BoVmZCdUU2cGMwNzdySi9GcDRZQ2hOdHdzWWJLZGQ4QmxMc3ViendNSFJ3K2w3Umt3Sy9XN1JBCnFTd1VNdmFLRWJON3JiRUM5NlllLzAyWHBTNldPREZDbWtqTUhTaUJBb0dBVmZyeHh3NENoYVFKTFB4a1Fyc1oKWGwrYjBzamFqRTI1OHJRMFU0aWl2eEt3QmlseUxmMmJjZ2FkUDJ2Z0VDTnQ4TXl5YVJtMnpoSzc4Nlo0NmhVMQprYVl0dFlaTHA2QWxTWXA5dDNTT0YxODBZdGM3RVBOYWNYdFRqam50QWJnQjBCUG9tbGdFaUphdHkrRGFzdGg1Ci9KRWZGYk43WE44a092RzcxNVZrQnFFQ2dZRUF4RksrNGZSWWdPenVHdDhPdlc3Vm9ZVytqbGVnSjhaRFduNVkKTndiWVBCZVRyQkxMSzRuYm12ZzhQZ2dKb1VNZ3ZkL1p5ZktJYkIvUmFmTTBlMVNhUW91U3lhMnN5WndSMGhlUAp4VHpZeTNSeXNxcUViZ1N6K3hWTFk3M1FNcjFlaDMwZnZ1RjRuMDZyUWtKNkNmdGZrajhXTUNaWUdrb0k0eFZMClB1ZWlGZ0VDZ1lBdjgyNUFiSmE3dzdZMDhtd2ZycDh0cFhmMk9yeVh2aGxIZUdGTFNGVmRrUWdObHFXVXJLOWcKRUVrSkRRYkNDWGtGMTdMbjFDb0hISHk0MWxKaTZWSnc4djJJMk1KaXJBMG83UDg5VWlKNXJRTlRzMVFXR3BNWQo3Q1dZRWNOc2YvTzlaM1FVa0R4OURUMUM3aE44d3ZDUEtZL3hyOWEyNDVibkVsVzVzTFZQOEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  MASTER_URL: https://gt2-control-plane-01.gt2software.dev:7002
